services:
  server:
    image: instay_v1_local-sv:latest
    container_name: instay_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    init: true
    restart: unless-stopped
    env_file:
      - ./backend/.env.local
    ports:
      - "8080:8080"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/configs/gcs.json:/app/configs/gcs.json
    networks:
      - frontend
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --tries=1 ${BE_HEALTHCHECK_URL} || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:15.1-alpine
    container_name: instay_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB_NAME:-db123}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-12345678}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5431:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PG_USER:-user123} -d ${PG_DB_NAME:-db123}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: instay_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${RD_PASSWORD:-12345678}
    networks:
      - backend
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: instay_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-user123}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD:-12345678}
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5671:5672"
      - "15671:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  client:
    image: instay_v1_local-cl:latest
    container_name: instay_client
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    init: true
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - frontend

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge